sign_off_message = "Thank you for learning more about AI today!Have a great rest of your day."
print("Welcome, you are speaking with Albert the AI Educator")
print("Lets get started!")
print("Press enter to start")
input()
print("First, what is your name?")
name = input("")
print(f"Hello {name},nice to meet you!")
print("How much do you know about AI, or Artificial intelligence? Answer with either A LOT, or NOT A LOT")
knowledge = input("")
print(f"That's perfect, knowing {knowledge} is perfectly amazing!")
print("Are you ready to learn about AI? press enter to continue.")
input("")
print("Here are some facts")
print("AI doesn't actually think, it predicts what the next word, or character will be in a sequence.")
input("")
print("The first chatbot was created in 1966, and it was named ELIZA. ELIZA was very simple, and just repeated what the user typed in, while also adding a sentence around it to make it seem like a human.")
input("")
print("AI needs a bunch of energy to run. When a computer is running, it heats up, and the most common way to cool the computer, is with water. This has led to water problems all over the world")
input("")
print("Thats all for today!")
print("I hope you learned a bit about AI today!")
input("")
print("Did you gain more understanding about AI today, and will you educate in the future?")
response = input("")
print(sign_off_message)